//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABSENCE
    {
        public string ID_ETUD { get; set; }
        public string ID_ELEM { get; set; }
        public Nullable<System.DateTime> DATE_ABS { get; set; }
        public Nullable<bool> IS_JUSTIF { get; set; }
        public string JUSTIFICATION { get; set; }
    
        public virtual ELEMENT ELEMENT { get; set; }
        public virtual ETUDIANT ETUDIANT { get; set; }
        public virtual ELEMENT ELEMENT1 { get; set; }
        public virtual ETUDIANT ETUDIANT1 { get; set; }
    }
}
