//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolDBEntities : DbContext
    {
        public SchoolDBEntities()
            : base("name=SchoolDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<ABSENCE> ABSENCE { get; set; }
        public virtual DbSet<ADMIN> ADMIN { get; set; }
        public virtual DbSet<DEPARTEMENT> DEPARTEMENT { get; set; }
        public virtual DbSet<ELEMENT> ELEMENT { get; set; }
        public virtual DbSet<ETUDIANT> ETUDIANT { get; set; }
        public virtual DbSet<FILLIERE> FILLIERE { get; set; }
        public virtual DbSet<MODULE> MODULE { get; set; }
        public virtual DbSet<NOTE> NOTE { get; set; }
        public virtual DbSet<PROF> PROF { get; set; }
        public virtual DbSet<VALIDATION> VALIDATION { get; set; }
    }
}
